@extends('layouts.app')
@section('content')
<style>
    .auth-wrap { min-height: calc(100vh - 120px); display:flex; align-items:center; }
    .auth-card { border:0; border-radius:20px; overflow:hidden; box-shadow:0 22px 48px rgba(15,23,42,.12); }
    .auth-left { background: linear-gradient(135deg, #1c4d95, #2f9f74); color:#fff; padding:30px; height:100%; }
    .auth-left h3 { font-weight:800; margin-bottom:8px; } .auth-left p { opacity:.9; margin-bottom:0; }
</style>
<div class="container auth-wrap"><div class="row justify-content-center w-100"><div class="col-lg-9 col-xl-8"><div class="card auth-card"><div class="row g-0"><div class="col-md-5 d-none d-md-block"><div class="auth-left h-100 d-flex flex-column justify-content-center"><h3>Create Account</h3><p>Set up a user account for access to the system.</p><hr class="border-light opacity-50 my-3"><small class="opacity-75">Admins can create either another admin or a cashier account.</small></div></div><div class="col-md-7"><div class="card-body p-4 p-lg-5"><div class="mb-3"><h4 class="fw-bold mb-1">Register</h4><small class="text-muted">Fill in the details below</small></div><form method="POST" action="{{ route('register') }}">@csrf<div class="mb-3"><label for="name" class="form-label fw-semibold">Name</label><input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label for="email" class="form-label fw-semibold">Email Address</label><input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label for="role" class="form-label fw-semibold">Role</label><select id="role" class="form-select @error('role') is-invalid @enderror" name="role" required><option value="cashier" {{ old('role', 'cashier') === 'cashier' ? 'selected' : '' }}>Cashier</option><option value="admin" {{ old('role') === 'admin' ? 'selected' : '' }}>Admin</option></select>@error('role')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label for="password" class="form-label fw-semibold">Password</label><input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label for="password-confirm" class="form-label fw-semibold">Confirm Password</label><input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password"></div><button type="submit" class="btn btn-primary w-100 py-2 fw-semibold">Create Account</button></form></div></div></div></div></div></div></div>
@endsection
